[package]
name = "summ-common"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
thiserror = "1.0"
dirs = { workspace = true }
anyhow = "1.0"

[dev-dependencies]
tempfile = "3.8"
